<a href="https://colab.research.google.com/github/Shashwat-006/Learning_PyTorch/blob/main/Learning_PyTorch_Basics_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Checking Basics**



In [1]:
import torch
print(torch.__version__)

2.9.0+cpu


In [2]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU.")

GPU not available. Using CPU.


## **Creating a TENSOR**

In [3]:
#using empty
torch.empty(2,3)

tensor([[6.7262e-44, 0.0000e+00, 6.7262e-44],
        [0.0000e+00, 3.1421e-40, 0.0000e+00]])

In [4]:
a=torch.empty(3,2)

#check typee
type(a)

torch.Tensor

In [5]:
#using zeros
torch.zeros(2,4)

#similar with ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
#using rand
torch.rand(2,3)

tensor([[0.8241, 0.6152, 0.4733],
        [0.6514, 0.0770, 0.2657]])

In [7]:
#use of seed
torch.rand(2,4)

tensor([[0.0525, 0.1331, 0.7711, 0.7508],
        [0.8187, 0.4661, 0.1953, 0.3363]])

In [8]:
#manual seed
torch.manual_seed(42)
torch.rand(2,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936]])

On using manual seed, we'll get same random values

In [9]:
torch.manual_seed(42)
torch.rand(2,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936]])

In [10]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
#other ways

#arange
print(torch.arange(1,11))

#using linspace
print(torch.linspace(0,10,10)) #0 se 10 tk ten equi-distant values

#using eye
print(torch.eye(3))

#using full
print(torch.full((2,3),6))

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[6, 6, 6],
        [6, 6, 6]])
