<a href="https://colab.research.google.com/github/Shashwat-006/Learning_PyTorch/blob/main/Learning_PyTorch_Basics_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

## **Tensor Shapes**

In [2]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [3]:
x.shape

torch.Size([2, 3])

**if we need another tensor of shape similar to any tensor**

In [4]:
torch.empty_like(x)

tensor([[136789884485008, 136789884485008,       173311120],
        [      115183024,               0,       171006688]])

In [5]:
torch.ones_like(x)
#similar with zeros_like

tensor([[1, 1, 1],
        [1, 1, 1]])

In [6]:
# torch.rand_like(x) this doesn't work becacuse of mismatching of data types
torch.rand_like(x, dtype=torch.float32)

tensor([[0.7762, 0.0619, 0.5950],
        [0.7403, 0.4515, 0.9140]])

## **Tensor DataTypes**

In [7]:
#find data type
x.dtype

torch.int64

In [8]:
#assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [9]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [10]:
#using "to"
x.to(torch.float32) #changes dtype of tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])