<a href="https://colab.research.google.com/github/Shashwat-006/Learning_PyTorch/blob/main/Learning_PyTorch_Basics_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NN Module**

In [1]:
import torch
import torch.nn as nn

## **Example 1.** assuming a binary classification problem that has 5 features and gives 1 output & uses sigmoid activation function.

In [2]:
#creating model class


class Model(nn.Module):
  def __init__(self, num_of_features):

    super().__init__()
    self.linear = nn.Linear(num_of_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [3]:
#creating a dummy dataset
dataset = torch.rand(10,5)

#create model
model = Model(dataset.shape[1])

#calling model for forward pass
model(dataset)    #model.forward(dataset) this can also work but this isn't standard way of calling forward pass in PyTorch

tensor([[0.6055],
        [0.5987],
        [0.5904],
        [0.6842],
        [0.6622],
        [0.6349],
        [0.6759],
        [0.6760],
        [0.6075],
        [0.6459]], grad_fn=<SigmoidBackward0>)

In [5]:
#show model weights
model.linear.weight

#similarly for bias
#model.linear.bias

Parameter containing:
tensor([[-0.0686,  0.3098, -0.0044,  0.2667,  0.2480]], requires_grad=True)

In order to Visualize the layers, we can use **summary** from **torchinfo**

In [6]:
!pip install torchinfo

In [7]:
from torchinfo import summary

In [8]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## **Example 2.** There's a hidden layer (ReLU as activation fn) with 3 neurons with their own bias  and 5 input features and 1 output

total we will have (5*3)+(3*1) = 18 weights and 4 bias

In [24]:
class Model(nn.Module):
  def __init__(self, num_of_features):

    super().__init__()
    # self.linear1 = nn.Linear(num_of_features, 3)      #raw basic code
    # self.relu = nn.ReLU()                             #raw basic code
    # self.linear2 = nn.Linear(3,1)                     #raw basic code
    # self.sigmoid = nn.Sigmoid()                       #raw basic code

    # WE WILL USE SEQUENTIAL CONTAINER FOR SIMPLIFYING CODE AND OPERATIONS

    self.network = nn.Sequential(
        nn.Linear(num_of_features, 3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self, features):
    # out = self.linear1(features)                      #raw basic code
    # out = self.relu(out)                              #raw basic code
    # out = self.linear2(out)                           #raw basic code
    # out = self.sigmoid(out)                           #raw basic code
    out = self.network(features)

    return out

In [40]:
#using same dummy dataset

model = Model(dataset.shape[1])

model(dataset)

tensor([[0.5048],
        [0.5048],
        [0.5048],
        [0.5048],
        [0.5048],
        [0.5048],
        [0.5048],
        [0.5048],
        [0.5048],
        [0.5048]], grad_fn=<SigmoidBackward0>)

In [41]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# **Working on Breast Cancer Data using NN Module**

Working on the same which I hard coded manually without using any modules previously

## **Pre-Processing**

In [42]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [43]:
data = pd.read_csv('/content/breast-cancer.csv')

In [44]:
Y = data['diagnosis']
X = data.drop(columns =['id','diagnosis'],axis=1)

In [45]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [46]:
scaler = StandardScaler()

In [47]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [48]:
encoder = LabelEncoder()

In [49]:
Y_train = encoder.fit_transform(Y_train)
Y_test = encoder.transform(Y_test)

In [54]:
X_train_tensor = torch.from_numpy(X_train)
X_train_tensor = X_train_tensor.float()
X_test_tensor = torch.from_numpy(X_test)
X_test_tensor = X_test_tensor.float()
Y_train_tensor = torch.from_numpy(Y_train)
Y_train_tensor = Y_train_tensor.float()
Y_test_tensor = torch.from_numpy(Y_test)
Y_test_tensor = Y_test_tensor.float()

## **UPDATION w.r.t previous**

In [67]:
class firstNN(nn.Module):
  def __init__(self, num_of_features):
    super().__init__()
    self.linear = nn.Linear(num_of_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out




In [68]:
learning_rate = 0.1
no_of_epochs = 40

In [69]:
# removing manual loss fn from class definition and using module's loss fn
loss_function = nn.BCELoss()

In [70]:
#creating model
model = firstNN(X_train_tensor.shape[1])

# using module's optimizer and removing manual one
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epochs in range(no_of_epochs):

  #forward pass
  y_pred = model(X_train_tensor)

  #loss calculation
  loss = loss_function(y_pred, Y_train_tensor.view(-1,1))

  #zero gradients so that gradients doesn't accumulate
  optimizer.zero_grad()

  #backward pass
  loss.backward()

  #parameters updation
  optimizer.step()

  #visualizing loss with each epoch
  print(f'Epoch: {epochs+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7125059962272644
Epoch: 2, Loss: 0.5373978018760681
Epoch: 3, Loss: 0.4440993368625641
Epoch: 4, Loss: 0.3871927857398987
Epoch: 5, Loss: 0.3485523462295532
Epoch: 6, Loss: 0.32030561566352844
Epoch: 7, Loss: 0.2985506057739258
Epoch: 8, Loss: 0.28113967180252075
Epoch: 9, Loss: 0.2667923867702484
Epoch: 10, Loss: 0.2546966075897217
Epoch: 11, Loss: 0.2443111538887024
Epoch: 12, Loss: 0.23526068031787872
Epoch: 13, Loss: 0.22727595269680023
Epoch: 14, Loss: 0.22015854716300964
Epoch: 15, Loss: 0.21375863254070282
Epoch: 16, Loss: 0.20796072483062744
Epoch: 17, Loss: 0.20267431437969208
Epoch: 18, Loss: 0.19782711565494537
Epoch: 19, Loss: 0.1933608502149582
Epoch: 20, Loss: 0.18922777473926544
Epoch: 21, Loss: 0.18538841605186462
Epoch: 22, Loss: 0.18180975317955017
Epoch: 23, Loss: 0.1784639060497284
Epoch: 24, Loss: 0.17532718181610107
Epoch: 25, Loss: 0.1723792403936386
Epoch: 26, Loss: 0.16960255801677704
Epoch: 27, Loss: 0.1669817864894867
Epoch: 28, Loss: 0.1645

In [71]:
model.linear.weight

Parameter containing:
tensor([[ 0.3792,  0.2906,  0.2242,  0.3617,  0.2824,  0.0332,  0.3811,  0.1236,
          0.1872, -0.1132,  0.3633, -0.0749,  0.1353,  0.2892, -0.1282,  0.0213,
          0.0339,  0.0371, -0.1393, -0.0064,  0.1871,  0.2517,  0.3561,  0.4224,
          0.1675,  0.1648,  0.1257,  0.1697,  0.1937,  0.0537]],
       requires_grad=True)

In [72]:
#model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor).round()
  accuracy = (y_pred == Y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy}')

Accuracy: 0.5369344353675842
