<a href="https://colab.research.google.com/github/Shashwat-006/Learning_PyTorch/blob/main/Learning_PyTorch_Basics_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# **Mathematical Operations**

## 1. Scalar Operations

In [2]:
x =torch.rand(2,2)
x

tensor([[0.2010, 0.4208],
        [0.3550, 0.4859]])

In [3]:
#addition
print(x + 2)

#subtraction
print(x - 2)

#multiplication
print(x * 2)

#division
print(x / 2)

#int division
print((x*100)//3)

#mod
print(((x*100)//3)%5)

#power
print(x**3)

tensor([[2.2010, 2.4208],
        [2.3550, 2.4859]])
tensor([[-1.7990, -1.5792],
        [-1.6450, -1.5141]])
tensor([[0.4020, 0.8416],
        [0.7099, 0.9719]])
tensor([[0.1005, 0.2104],
        [0.1775, 0.2430]])
tensor([[ 6., 14.],
        [11., 16.]])
tensor([[1., 4.],
        [1., 1.]])
tensor([[0.0081, 0.0745],
        [0.0447, 0.1147]])


## 2. Element-wise Operation

In [4]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.3798, 0.1427, 0.6904],
        [0.5150, 0.9197, 0.7914]])
tensor([[0.8252, 0.7028, 0.9851],
        [0.6889, 0.3191, 0.1404]])


In [5]:
# add
# torch.add(a,b) or
a + b

# subtract
a - b

# multiply
a * b

# division
a / b

# mod
a % b

# power
a ** b

tensor([[0.4498, 0.2545, 0.6942],
        [0.6331, 0.9737, 0.9677]])

In [6]:
c = torch.tensor([1, -2, 3, -4])

# abs (absolute value)
torch.abs(c)

tensor([1, 2, 3, 4])

In [7]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [8]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [9]:
#ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [10]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [11]:
#clamp
torch.clamp(d, min=2, max=3) #elements less than 'min' becomes 'min' & greater than 'max' becomes 'max'

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## 3. Reduction Operation

In [12]:
e = torch.randint(size=(2,3), low=0, high=10)
e

tensor([[8, 4, 9],
        [3, 2, 6]])

In [13]:
#sum
torch.sum(e)

#sum along column
torch.sum(e, dim=0)

#sum along row
torch.sum(e, dim=1)

tensor([21, 11])

In [14]:
f = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

#mean
torch.mean(f) #only supports floating or complex no.

#mean along col
torch.mean(f, dim=0)

tensor([6.5000, 4.5000, 6.0000])

In [15]:
#median
torch.median(e)

tensor(4)

In [16]:
#max and min
torch.max(e)
torch.min(e, dim=1)

torch.return_types.min(
values=tensor([4, 2]),
indices=tensor([1, 1]))

In [17]:
#product
torch.prod(e)

tensor(10368)

In [18]:
#std deviation
torch.std(f) #only supports floating or complex no.

tensor(2.2509)

In [19]:
#variance
torch.var(f, dim=0)

tensor([12.5000,  0.5000,  8.0000])

In [20]:
#argmax
torch.argmax(e) #gives index of highest no.

tensor(2)

In [21]:
#argmin
torch.argmin(e)

tensor(4)

## 4. Matrix Operations

In [22]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[2, 3, 6],
        [5, 7, 7]])
tensor([[6, 1],
        [1, 4],
        [2, 3]])


In [23]:
#matrix multiplication

torch.matmul(f,g)

#torch.matmul(g,f)

tensor([[27, 32],
        [51, 54]])

In [24]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

#dot product
torch.dot(vector1, vector2)

tensor(11)

In [25]:
#transpose
torch.transpose(f, 0, 1) #(matrix , dim1, dim2 (kis dim ko kis dim me krna h))

tensor([[2, 5],
        [3, 7],
        [6, 7]])

In [26]:
h = torch.randint(0, 10, (3,3)).to(torch.float32) #randint accepts arg as follows (low, high, size) by default
h

tensor([[3., 1., 5.],
        [1., 6., 4.],
        [7., 1., 8.]])

In [27]:
#determinant
torch.det(h)

tensor(-53.0000)

In [28]:
#inverse
torch.inverse(h)

tensor([[-0.8302,  0.0566,  0.4906],
        [-0.3774,  0.2075,  0.1321],
        [ 0.7736, -0.0755, -0.3208]])

## 5. Comparision Opertaions

In [29]:
i = torch.randint(0, 10, (2,3))
j = torch.randint(0, 10, (2,3))

print(i)
print(j)

tensor([[2, 9, 1],
        [5, 5, 6]])
tensor([[3, 1, 5],
        [8, 9, 0]])


In [30]:
#greater than
i > j

#less than
i < j

#equal to
i == j

#Not equal to
i != j

#less than equal to
i <= j

#greater than equal to
i >= j

tensor([[False,  True, False],
        [False, False,  True]])

## 6. Special Functions

In [31]:
k = torch.randint(0,10,(2,3))
k

tensor([[0, 0, 7],
        [5, 6, 7]])

In [32]:
#log
torch.log(k)

tensor([[  -inf,   -inf, 1.9459],
        [1.6094, 1.7918, 1.9459]])

In [33]:
#exp
torch.exp(k)

tensor([[1.0000e+00, 1.0000e+00, 1.0966e+03],
        [1.4841e+02, 4.0343e+02, 1.0966e+03]])

In [34]:
#sqrt
torch.sqrt(k)

tensor([[0.0000, 0.0000, 2.6458],
        [2.2361, 2.4495, 2.6458]])

In [35]:
#sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.5000, 0.9991],
        [0.9933, 0.9975, 0.9991]])

In [36]:
k = torch.randint(0, 10, (2,3), dtype=torch.float32)

#softmax
torch.softmax(k, dim=0) #supports floating value and need a dim to apply softmax

tensor([[0.9820, 0.1192, 0.9975],
        [0.0180, 0.8808, 0.0025]])

In [37]:
#relu
torch.relu(k)

tensor([[6., 4., 9.],
        [2., 6., 3.]])

# **Inplace Operations**

In [38]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[5.5385e-01, 4.0013e-01, 7.8643e-01],
        [3.6743e-01, 5.9779e-01, 6.0087e-04]])
tensor([[0.8092, 0.3704, 0.7790],
        [0.7015, 0.2513, 0.5372]])


underscore ( _ ) represents inplace operation

In [39]:
m.add_(n) #add m and n & stores the result in 'm'
print(m)

tensor([[1.3631, 0.7705, 1.5654],
        [1.0689, 0.8491, 0.5378]])


In [40]:
m.relu_() #stores the result after applying relu in 'm'
print(m)

tensor([[1.3631, 0.7705, 1.5654],
        [1.0689, 0.8491, 0.5378]])
