<a href="https://colab.research.google.com/github/Shashwat-006/Learning_PyTorch/blob/main/Learning_PyTorch_Basics_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# **Copying a TENSOR**

In [2]:
a = torch.rand(2,3)
a

tensor([[0.0075, 0.5169, 0.9793],
        [0.7671, 0.7822, 0.6810]])

In [3]:
b = a #there's a problem with this
b

tensor([[0.0075, 0.5169, 0.9793],
        [0.7671, 0.7822, 0.6810]])

In [4]:
a[0][0] = 0 #if we do some change in a, it's occurs in b as well
b

tensor([[0.0000, 0.5169, 0.9793],
        [0.7671, 0.7822, 0.6810]])

In [5]:
#this is how we prove it
print(id(a))
print(id(b))

134448587060912
134448587060912


This means that assignment operator ( = ), doesn't copy rather it makes the variable to refer to the location where the tensor is stored

**This is how we copy**

In [6]:
b = a.clone()
b

tensor([[0.0000, 0.5169, 0.9793],
        [0.7671, 0.7822, 0.6810]])

In [7]:
a[0][1] = 0
print(a)
print(b)

tensor([[0.0000, 0.0000, 0.9793],
        [0.7671, 0.7822, 0.6810]])
tensor([[0.0000, 0.5169, 0.9793],
        [0.7671, 0.7822, 0.6810]])


# **Tensor Operations on GPU**

In [8]:
torch.cuda.is_available()

True

In [9]:
device = torch.device('cuda')

In [10]:
#creating new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.6285, 0.8084, 0.1865],
        [0.4580, 0.7272, 0.4548]], device='cuda:0')

In [11]:
a = torch.rand(2,3)
a

tensor([[0.1991, 0.4041, 0.0572],
        [0.4225, 0.0328, 0.5149]])

In [12]:
#moving an existing tensor to GPU
a.to(device)

tensor([[0.1991, 0.4041, 0.0572],
        [0.4225, 0.0328, 0.5149]], device='cuda:0')

# **Reshaping Tensors**

In [13]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
#reshape
a.reshape(2,2,4) #or (2,2,2,2)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [15]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
b = torch.rand(2,3,4)
b

tensor([[[0.5020, 0.9797, 0.4510, 0.9475],
         [0.0396, 0.1327, 0.1634, 0.3851],
         [0.2801, 0.6195, 0.2646, 0.4439]],

        [[0.7908, 0.6702, 0.9590, 0.7394],
         [0.9789, 0.8966, 0.6677, 0.0291],
         [0.5101, 0.6293, 0.8517, 0.4990]]])

In [17]:
#permute
b.permute(2,0,1) #there 2,0,1 are indices of shape of the tensor

tensor([[[0.5020, 0.0396, 0.2801],
         [0.7908, 0.9789, 0.5101]],

        [[0.9797, 0.1327, 0.6195],
         [0.6702, 0.8966, 0.6293]],

        [[0.4510, 0.1634, 0.2646],
         [0.9590, 0.6677, 0.8517]],

        [[0.9475, 0.3851, 0.4439],
         [0.7394, 0.0291, 0.4990]]])

In [18]:
#unsqeeze
#typical image size = (216,216,3)

c=torch.rand(216,216,3)
c.unsqueeze(0).shape   #We pass the index where new dim (1) is to be added as argument

torch.Size([1, 216, 216, 3])

In [19]:
#squeeze -> this only removes a dim if dimension at given argument is 1

d = torch.rand(2,20)
print(d.squeeze(0).shape)

e = torch.rand(3,1,3)
print(e.squeeze(1).shape)

torch.Size([2, 20])
torch.Size([3, 3])


# **NUMPY and PYTORCH**

In [20]:
import numpy as np

In [21]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [22]:
#converting a tensor to numpy array
b = a.numpy()
b

array([1, 2, 3])

In [23]:
type(b)

numpy.ndarray

In [24]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [25]:
#converting a numpy array to tensor
torch.from_numpy(c)

tensor([1, 2, 3])